Config = Config or {}

Config.ShortCalls = false -- Dispatch notifications are sent containing only the alert name, omitting additional details. For more information, the dispatch menu can be accessed.  
Config.Debug = false -- Enables debug and send alerts when leo break the law.
Config.PhoneBridge = false -- enables bridge between phone and menu (deleting, creating)

Config.RespondKeybind = 'E'
Config.OpenDispatchMenu = 'F11'
Config.AlertTime = 10     -- Specify the duration for the alert to appear on the screen. The default time is 5 seconds for all alerts. To set a different duration for specific alerts, change the value in `alertTime = nil` found in the alerts.lua file.

Config.MaxCallList = 25 -- maximum dispatch calls in dispatch list
Config.OnDutyOnly = false -- Set true if only on duty players can see the alert
Config.Jobs = { -- Jobs that can access the dispatch menu
    'fib',
    'gouvernement',
    'sheriff',
    'police',
}

Config.DefaultAlertsDelay = 15 -- Delay between each default alert, prevent spamming
Config.DefaultAlerts = {
    Speeding = false,
    Shooting = true,
    Autotheft = false,
    Melee = false,
    PlayerDowned = false,
    Explosion = false
}

Config.MinOffset = 1
Config.MaxOffset = 120

Config.PhoneRequired = true -- Set true if only can use 911/311 command when got a phone on inventory.
Config.PhoneItems = { -- Add the entire list of your phone items.
    "phone",
}

-- Locations for the Hunting Zones and No Dispatch Zones( Label: Name of Blip // Radius: Radius of the Alert and Blip)
Config.EnableHuntingBlip = false
Config.Locations = {
    ["HuntingZones"] = {
        [1] = {label = "Hunting Zone", radius = 650.0, coords = vector3(-938.61, 4823.99, 313.92)},
    },
    ["NoDispatchZones"] = {
        [1] = {label = "Ammunation 1", coords = vector3(13.53, -1097.92, 29.8), length = 14.0, width = 5.0, heading = 70, minZ = 28.8, maxZ = 32.8},
        [2] = {label = "Ammunation 2", coords = vector3(821.96, -2163.09, 29.62), length = 14.0, width = 5.0, heading = 270, minZ = 28.62, maxZ = 32.62},
    },
}

-- Whitelist Guns that do not send shooting alerts
Config.WeaponWhitelist = {
    'WEAPON_GRENADE',
    'WEAPON_BZGAS',
    'WEAPON_MOLOTOV',
    'WEAPON_STICKYBOMB',
    'WEAPON_PROXMINE',
    'WEAPON_SNOWBALL',
    'WEAPON_PIPEBOMB',
    'WEAPON_BALL',
    'WEAPON_SMOKEGRENADE',
    'WEAPON_FLARE',
    'WEAPON_PETROLCAN',
    'WEAPON_FIREEXTINGUISHER',
    'WEAPON_HAZARDCAN',
    'WEAPON_RAYCARBINE',
    'WEAPON_STUNGUN'
}

Config.Blips = {
    ['vehicleshots'] = { -- Need to match the codeName in alerts.lua
        radius = 0,
        sprite = 119,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['shooting'] = {
        radius = 0,
        sprite = 110,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['speeding'] = {
        radius = 0,
        sprite = 326,
        color = 84,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['fight'] = {
        radius = 0,
        sprite = 685,
        color = 69,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['civdown'] = {
        radius = 0,
        sprite = 126,
        color = 3,
        scale = 0.8,
        length = 2,
        sound = 'dispatch',
        offset = false,
        flash = false
    },
    ['civdead'] = {
        radius = 0,
        sprite = 126,
        color = 3,
        scale = 0.8,
        length = 2,
        sound = 'dispatch',
        offset = false,
        flash = false
    },
    ['911call'] = {
        radius = 0,
        sprite = 480,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['311call'] = {
        radius = 0,
        sprite = 480,
        color = 3,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['officerdown'] = {
        radius = 15.0,
        sprite = 526,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = true
    },
    ['officerbackup'] = {
        radius = 15.0,
        sprite = 526,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = true
    },
    ['officerdistress'] = {
        radius = 15.0,
        sprite = 526,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = true
    },
    ['OfficerPanic'] = {
        radius = 15.0,
        sprite = 526,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = true
    },
    ['emsdown'] = {
        radius = 15.0,
        sprite = 526,
        color = 3,
        scale = 0.8,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = false
    },
    ['hunting'] = {
        radius = 0,
        sprite = 141,
        color = 2,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['storerobbery'] = {
        radius = 0,
        sprite = 52,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['bankrobbery'] = {
        radius = 0,
        sprite = 207,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['pawnshoproberry'] = {
        radius = 0,
        sprite = 207,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['atmrobbery'] = {
        radius = 0,
        sprite = 207,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['paletobankrobbery'] = {
        radius = 0,
        sprite = 500,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['pacificbankrobbery'] = {
        radius = 0,
        sprite = 500,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['prisonbreak'] = {
        radius = 0,
        sprite = 189,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['vangelicorobbery'] = {
        radius = 0,
        sprite = 617,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['houserobbery'] = {
        radius = 0,
        sprite = 40,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['lockpick'] = {
        radius = 0,
        sprite = 40,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['suspicioushandoff'] = {
        radius = 120.0,
        sprite = 469,
        color = 52,
        scale = 0,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = true,
        flash = false
    },
    ['yachtheist'] = {
        radius = 0,
        sprite = 455,
        color = 60,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['vehicletheft'] = {
        radius = 0,
        sprite = 595,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['signrobbery'] = {
        radius = 0,
        sprite = 358,
        color = 60,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['susactivity'] = {
        radius = 0,
        sprite = 66,
        color = 37,
        scale = 0.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    -- Rainmad Scripts
    ['artgalleryrobbery'] = {
        radius = 0,
        sprite = 269,
        color = 59,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['humanelabsrobbery'] = {
        radius = 0,
        sprite = 499,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['trainrobbery'] = {
        radius = 0,
        sprite = 667,
        color = 78,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['vanrobbery'] = {
        radius = 0,
        sprite = 67,
        color = 59,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['undergroundrobbery'] = {
        radius = 0,
        sprite = 486,
        color = 59,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['drugboatrobbery'] = {
        radius = 0,
        sprite = 427,
        color = 26,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['unionrobbery'] = {
        radius = 0,
        sprite = 500,
        color = 60,
        scale = 0.8,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['carboosting'] = {
        radius = 0,
        sprite = 595,
        color = 60,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['carjack'] = {
        radius = 0,
        sprite = 595,
        color = 60,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['explosion'] = {
        radius = 0,
        sprite = 436,
        color = 1,
        scale = 0.8,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    }
}

Config.Colors = {
	['1'] = "Metallic Graphite Schwarz",
	['2'] = "Metallic Schwarz Steal",
	['3'] = "Metallic Dunkel Silber",
	['4'] = "Metallic Silber",
	['5'] = "Metallic Blau Silber",
	['6'] = "Metallic Stahl Grau",
	['7'] = "Metallic Shadow Silber",
	['8'] = "Metallic Stein Silber",
	['9'] = "Metallic Midnight Silber",
	['10'] = "Metallic Gun Metal",
	['11'] = "Metallic Anthracite Grau",
	['12'] = "Matt Schwarz",
	['13'] = "Matt Grau",
	['14'] = "Matt Light Grau",
	['15'] = "Util Schwarz",
	['16'] = "Util Schwarz Poly",
	['17'] = "Util Dunkel Silber",
	['18'] = "Util Silber",
	['19'] = "Util Gun Metal",
	['20'] = "Util Shadow Silber",
	['21'] = "Worn Schwarz",
	['22'] = "Worn Graphite",
	['23'] = "Worn Silber Grau",
	['24'] = "Worn Silber",
	['25'] = "Worn Blau Silber",
	['26'] = "Worn Shadow Silber",
	['27'] = "Metallic Rot",
	['28'] = "Metallic Torino Rot",
	['29'] = "Metallic Formula Rot",
	['30'] = "Metallic Blaze Rot",
	['31'] = "Metallic Graceful Rot",
	['32'] = "Metallic Garnet Rot",
	['33'] = "Metallic Desert Rot",
	['34'] = "Metallic Cabernet Rot",
	['35'] = "Metallic Candy Rot",
	['36'] = "Metallic Sunrise Orange",
	['37'] = "Metallic Classic Gold",
	['38'] = "Metallic Orange",
	['39'] = "Matt Rot",
	['40'] = "Matt Dunkel Rot",
	['41'] = "Matt Orange",
	['42'] = "Matt Gelb",
	['43'] = "Util Rot",
	['44'] = "Util Hell Rot",
	['45'] = "Util Garnet Rot",
	['46'] = "Worn Rot",
	['47'] = "Worn Gold Rot",
	['48'] = "Worn Dunkel Rot",
	['49'] = "Metallic Dunkel Grün",
	['50'] = "Metallic Racing Grün",
	['51'] = "Metallic Sea Grün",
	['52'] = "Metallic Olive Grün",
	['53'] = "Metallic Grün",
	['54'] = "Metallic Gasoline Blau Grün",
	['55'] = "Matt Lime Grün",
	['56'] = "Util Dunkel Grün",
	['57'] = "Util Grün",
	['58'] = "Worn Dunkel Grün",
	['59'] = "Worn Grün",
	['60'] = "Worn Sea Wash",
	['61'] = "Metallic Midnight Blau",
	['62'] = "Metallic Dunkel Blau",
	['63'] = "Metallic Saxony Blau",
	['64'] = "Metallic Blau",
	['65'] = "Metallic Mariner Blau",
	['66'] = "Metallic Harbor Blau",
	['67'] = "Metallic Diamond Blau",
	['68'] = "Metallic Surf Blau",
	['69'] = "Metallic Nautical Blau",
	['70'] = "Metallic Hell Blau",
	['71'] = "Metallic Violett Blau",
	['72'] = "Metallic Spinnaker Blau",
	['73'] = "Metallic Ultra Blau",
	['74'] = "Metallic Hell Blau",
	['75'] = "Util Dunkel Blau",
	['76'] = "Util Midnight Blau",
	['77'] = "Util Blau",
	['78'] = "Util Sea Foam Blau",
	['79'] = "Uil Lightning Blau",
	['80'] = "Util Maui Blau Poly",
	['81'] = "Util Hell Blau",
	['82'] = "Matt Dunkel Blau",
	['83'] = "Matt Blau",
	['84'] = "Matt Midnight Blau",
	['85'] = "Worn Dunkel Blau",
	['86'] = "Worn Blau",
	['87'] = "Worn Light Blau",
	['88'] = "Metallic Taxi Gelb",
	['89'] = "Metallic Race Gelb",
	['90'] = "Metallic Bronze",
	['91'] = "Metallic Gelb Bird",
	['92'] = "Metallic Lime",
	['93'] = "Metallic Champagne",
	['94'] = "Metallic Pueblo Beige",
	['95'] = "Metallic Dunkel Ivory",
	['96'] = "Metallic Choco Braun",
	['97'] = "Metallic Gold Braun",
	['98'] = "Metallic Light Braun",
	['99'] = "Metallic Straw Beige",
	['100'] = "Metallic Moss Braun",
	['101'] = "Metallic Biston Braun",
	['102'] = "Metallic Beechwood",
	['103'] = "Metallic Dunkel Beechwood",
	['104'] = "Metallic Choco Orange",
	['105'] = "Metallic Beach Sand",
	['106'] = "Metallic Sun Bleeched Sand",
	['107'] = "Metallic Cream",
	['108'] = "Util Braun",
	['109'] = "Util Medium Braun",
	['110'] = "Util Light Braun",
	['111'] = "Metallic Weiß",
	['112'] = "Metallic Frost Weiß",
	['113'] = "Worn Honey Beige",
	['114'] = "Worn Braun",
	['115'] = "Worn Dunkel Braun",
	['116'] = "Worn straw Beige",
	['117'] = "Brushed Steel",
	['118'] = "Brushed Schwarz steel",
	['119'] = "Brushed Aluminium",
	['120'] = "Chrome",
	['121'] = "Worn Off Weiß",
	['122'] = "Off Weiß",
	['123'] = "Worn Orange",
	['124'] = "Worn Light Orange",
	['125'] = "Metallic Securicor Grün",
	['126'] = "Worn Taxi Gelb",
	['127'] = "Polizei Blau",
	['128'] = "Matt Grün",
	['129'] = "Matt Braun",
	['130'] = "Worn Orange",
	['131'] = "Matt Weiß",
	['132'] = "Worn Weiß",
	['133'] = "Worn Olive Army Grün",
	['134'] = "Pure Weiß",
	['135'] = "Hot Pink",
	['136'] = "Lachs Pink",
	['137'] = "Metallic Vermillion Pink",
	['138'] = "Orange",
	['139'] = "Grün",
	['140'] = "Blau",
	['141'] = "Mettalic Schwarz Blau",
	['142'] = "Metallic Schwarz Violett",
	['143'] = "Metallic Schwarz Rot",
	['144'] = "Jäger Grün",
	['145'] = "Metallic Violett",
	['146'] = "Metaillic V Dunkel Blau",
	['147'] = "MODSHOP Schwarz",
	['148'] = "Matt Violett",
	['149'] = "Matt Dunkel Violett",
	['150'] = "Metallic Lava Rot",
	['151'] = "Matt Forest Grün",
	['152'] = "Matt Olive Drab",
	['153'] = "Matt Desert Braun",
	['154'] = "Matt Desert Tan",
	['155'] = "Matt Foilage Grün",
	['156'] = "Legierung",
	['157'] = "Epsilon Blau",
	['158'] = "Pures Gold",
	['159'] = "Gebürstetes Gold",
    ['160'] = "MP100",
}
